- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  vars:
    app_owner: vagrant
    app_group: vagrant
    code_root: /app/
    app_root: "{{ code_root }}django-wagtail-shop/demo/"
    app_name: demo
    app_version: 0.0.1
    python_major_version: 3
    python_version: 3.6
    python_venv_path: "{{ code_root }}pyenv{{ python_version }}"
    pip_requirements_path: "{{ app_root }}../pip-requirements.txt"
    server_name: example.com
    database_user: example
    database_pass: test123
    database_name: example
  tasks:
    - name: Compile python package from source
      command: "python {{ app_root }}../setup.py sdist"
      become: "{{ app_owner }}"
    - name: Pip Install shop from build
      pip:
        name: "{{ app_root }}../dist/django-wagtail-shop-{{ app_version }}.tar.gz"
        virtualenv: "{{ python_venv_path }}"
        virtualenv_python: "python{{ python_version }}"
      when: pip_requirements_path is defined and python_venv_path is defined and python_version is defined
      become_user: "{{ app_owner }}"
