- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  vars:
    database_name: demo
  tasks:
    - name: Dump database
      command: "pg_dump -f /app/django-wagtail-shop/db_dump.sql -c -C -x -O {{ database_name }}"
      become: postgres
